#!/usr/bin/ash

run_latehook() {
    mount -o remount,rw /run/archiso/img_dev

    mkdir /new_root/Media
    #mkdir /Media/Eloquent\ OS
    mkdir /new_root/System
    mkdir /new_root/Settings
    mkdir /new_root/Library
    mkdir /new_root/Library/Apps
    mkdir /new_root/Users
    mkdir /new_root/Apps
    ​
    #mount --move /run/archiso/img_dev /Media/Eloquent\ OS

    mount --bind /run/archiso/img_dev/System /new_root/System

    mount --bind /run/archiso/img_dev/Settings /new_root/Settings

    mount --bind /run/archiso/img_dev/Library /new_root/Library

    mount --bind /run/archiso/img_dev/Users /new_root/Users

    mount --bind /run/archiso/img_dev/Apps /new_root/Apps

    mount -t overlay -o lowerdir=/run/archiso/sfs/airootfs/etc,upperdir=/run/archiso/img_dev/Settings,workdir=/run/archiso/img_dev/Work/Settings overlay /new_root/etc

    mount -t overlay -o lowerdir=/run/archiso/sfs/airootfs/var,upperdir=/run/archiso/img_dev/System/Data,workdir=/run/archiso/img_dev/Work/System/Data overlay /new_root/var

    mount -t overlay -o lowerdir=/run/archiso/sfs/airootfs/usr/share/applications,upperdir=/run/archiso/img_dev/Library/Apps,workdir=/run/archiso/img_dev/Work/Library/Apps overlay /new_root/usr/share/applications
}
